services:
  # --- NUEVO SERVICIO DE BASE DE DATOS ---
  mysql-server:
    image: mysql:8.0
    container_name: perrones_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permite el DB_PASSWORD vacío
    volumes:
      - ./databases:/docker-entrypoint-initdb.d # Carpeta con tus .sql
      - mysql_data:/var/lib/mysql

  # --- TUS MICROSERVICIOS ---
  productos:
    image: ms-productos
    build: ./productos
    container_name: ms-productos
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql-server # <-- Cambiado
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: perrones
      PORT: 3001
    depends_on:
      - mysql-server # <-- Añadido

  usuarios:
    image: ms-usuarios
    build: ./usuarios
    container_name: ms-usuarios
    ports:
      - "3003:3003"
    environment:
      DB_HOST: mysql-server # <-- Cambiado
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: usuarios
      PORT: 3003
    depends_on:
      - mysql-server # <-- Añadido

  ordenes:
    image: ms-ordenes
    build: ./ordenes
    container_name: ms-ordenes
    ports:
      - "3002:3002"
    environment:
      DB_HOST: mysql-server # <-- Cambiado
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: ordenes
      PORT: 3002
      PRODUCTOS_URL: http://productos:3001
    depends_on:
      - mysql-server # <-- Añadido
      - productos

  facturacion:
    image: ms-facturacion
    build: ./facturacion
    container_name: ms-facturacion
    ports:
      - "3004:3004"
    environment:
      DB_HOST: mysql-server # <-- Cambiado
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: facturacion
      PORT: 3004
      ORDENES_URL: http://ordenes:3002
    depends_on:
      - mysql-server # <-- Añadido
      - ordenes

  frontend:
    image: frontend-perrones
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - productos
      - usuarios
      - ordenes
      - facturacion

# --- VOLUMEN PARA LA BASE DE DATOS ---
volumes:
  mysql_data:
